# Generated by Django 5.1.4 on 2024-12-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=100, unique=True, verbose_name='Зав. № машины')),
                ('machine_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель техники')),
                ('engine_model', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission_model', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission_number', models.CharField(blank=True, max_length=100, null=True)),
                ('drive_axle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('drive_axle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('steerable_axle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('steerable_axle_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=300, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('service_company', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
