# Generated by Django 5.1.4 on 2024-12-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(blank=True, null=True)),
                ('operating_time', models.PositiveIntegerField(default=0)),
                ('failure_node', models.CharField(max_length=200)),
                ('failure_description', models.TextField(blank=True, null=True)),
                ('recovery_method', models.CharField(blank=True, max_length=200, null=True)),
                ('used_parts', models.TextField(blank=True, null=True)),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('downtime', models.PositiveIntegerField(default=0)),
                ('service_company', models.CharField(blank=True, max_length=200, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='machines.machine')),
            ],
        ),
    ]
