# Generated by Django 5.1.4 on 2024-12-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_type', models.CharField(max_length=100)),
                ('date_performed', models.DateField(blank=True, null=True)),
                ('operating_time', models.PositiveIntegerField(default=0)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('service_company', models.CharField(blank=True, max_length=200, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_records', to='machines.machine')),
            ],
        ),
    ]
